export {
  type OtelParams,
  type InitResult,
  type Fields,
  type TraceOptions,
  type InstrumentOptions,
  TracingBuilder,
  Logger,
  Metrics,
  TimedHistogram,
  getLogger,
  getMeter,
  getTracer,
  createMetrics,
  withSpan,
  withSpanSync,
} from "./tracing/index.js";
